# Generated by Django 2.1 on 2021-07-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_recipeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='property',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='directions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredients',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
