# Generated by Django 2.1.5 on 2021-07-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_auto_20210706_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='property',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='directions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='name',
            field=models.TextField(),
        ),
    ]
